[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sei-anonimizer"
version = "1.0.2"
dependencies = [
    "pymupdf",
    "pandas"
]
description = "Ferramenta para anonimização de documentos com foco no SEI."
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]
include = ["sei_anonimizer*"]

[tool.setuptools.package-data]
sei-anonimizer = ["*.png"]